// api/_ai.ts
// Background LLM layer — Groq → Cerebras → Gemini → deterministic fallback.
//
// All calls are:
//   1. Cache-checked first (llm_cache table, keyed by cache_key)
//   2. Generated by the cheapest available free-tier API
//   3. Stored back to cache so the same prompt is never regenerated
//
// Cost on free tiers (all $0):
//   Groq       — unlimited RPM on Llama 3.1 8B (fast, <1s)
//   Cerebras   — 1M tokens/month on Llama 3.1 8B (batch jobs)
//   Gemini     — 1500 req/day on gemini-1.5-flash (fallback)
//
// ─── What gets generated ──────────────────────────────────────────────
//
//  type: "loot_name"     → creative weapon/armor name + 1-line flavor text
//  type: "enemy_name"    → enemy name + short lore sentence
//  type: "boss_name"     → boss name + 2-line lore + ability description
//  type: "summon_personality" → hero personality + unique trait name
//  type: "chapter"       → story chapter text based on player alignment + choice
//
// POST { type, data: { ... } }
// Returns { text, cached: bool, api: string }
//
// Called internally from _battle.ts / _loot.ts / future summon endpoint.
// Can also be called directly for chapter generation.

import { Pool } from '@neondatabase/serverless';
import { VercelRequest, VercelResponse } from '@vercel/node';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

// ── Types ─────────────────────────────────────────────────────────────

type AiType =
  | 'loot_name'
  | 'enemy_name'
  | 'boss_name'
  | 'summon_personality'
  | 'chapter';

interface AiRequest { type: AiType; data: Record<string, any>; }

// ── Cache ─────────────────────────────────────────────────────────────

async function checkCache(key: string): Promise<string | null> {
  const res = await pool.query(
    `SELECT generated_text FROM llm_cache
     WHERE cache_key = $1
       AND (expires_at IS NULL OR expires_at > NOW())`,
    [key]
  );
  if (res.rows.length) {
    // Bump hit count (fire-and-forget)
    pool.query(
      `UPDATE llm_cache SET hit_count = hit_count + 1 WHERE cache_key = $1`,
      [key]
    ).catch(() => {});
    return res.rows[0].generated_text;
  }
  return null;
}

async function writeCache(
  key: string, type: string, text: string,
  tokens: number, api: string,
  ttlHours: number | null = null
): Promise<void> {
  const expires = ttlHours
    ? `NOW() + INTERVAL '${ttlHours} hours'`
    : 'NULL';
  await pool.query(
    `INSERT INTO llm_cache (cache_type, cache_key, generated_text, tokens_used, api_used, expires_at)
     VALUES ($1, $2, $3, $4, $5, ${expires})
     ON CONFLICT (cache_key) DO UPDATE
       SET generated_text = EXCLUDED.generated_text,
           tokens_used    = EXCLUDED.tokens_used,
           api_used       = EXCLUDED.api_used,
           hit_count      = 0`,
    [type, key, text, tokens, api]
  );
}

// ── Prompt builders ───────────────────────────────────────────────────

function buildPrompt(type: AiType, data: Record<string, any>): string {
  switch (type) {
    case 'loot_name':
      return `You are a dark fantasy item namer. Generate a creative name and one-line flavor text for this item.
Item type: ${data.armor_type}
Rarity: ${data.rarity}
Primary stat bonus: +${data.primary_stat_value} ${data.primary_stat}
Respond in exactly this format (no other text):
NAME: <item name>
FLAVOR: <one sentence of flavor text, max 15 words>`;

    case 'enemy_name':
      return `You are a dark fantasy game writer. Generate a name and one-sentence lore for an enemy.
Enemy level: ${data.level}
Biome/context: ${data.context ?? 'ancient ruins'}
Respond in exactly this format:
NAME: <enemy name>
LORE: <one sentence, max 15 words>`;

    case 'boss_name':
      return `You are a dark fantasy game writer. Generate a boss name, two-line lore, and one special ability name.
Boss level: ${data.level}
Has reality shatter: ${data.has_reality_shatter}
Has void evasion: ${data.has_void_evasion}
Respond in exactly this format:
NAME: <boss name>
LORE: <two sentences, max 30 words total>
ABILITY: <special ability name, 2-4 words>`;

    case 'summon_personality':
      return `You are a dark fantasy character writer. Generate a personality and unique trait for a summoned hero.
Hero class: ${data.class_name}
Tier: ${data.tier}
Rarity: ${data.rarity}
Respond in exactly this format:
PERSONALITY: <one sentence describing personality, max 20 words>
TRAIT: <unique trait name, 2-4 words>`;

    case 'chapter':
      return `You are writing a dark cultivation fantasy story. Write a story chapter of 3-4 sentences.
Player alignment: ${data.alignment ?? 'Neutral'}
Previous choice: ${data.previous_choice ?? 'accepted the offer'}
Chapter number: ${data.chapter_number}
Then present exactly 3 choices the player can make (short, 3-6 words each).
Respond in exactly this format:
STORY: <3-4 sentences of story text>
CHOICE_A: <choice>
CHOICE_B: <choice>
CHOICE_C: <choice>`;

    default:
      return `Generate a short dark fantasy name.`;
  }
}

// ── Deterministic fallbacks (used when all APIs fail) ─────────────────

function deterministicFallback(type: AiType, data: Record<string,any>): string {
  switch (type) {
    case 'loot_name':
      return `NAME: ${data.rarity} ${data.armor_type ?? 'Blade'} of the Void\nFLAVOR: Forged in darkness, its power resonates with the bearer's will.`;
    case 'enemy_name':
      return `NAME: Corrupted Shade Lv${data.level}\nLORE: A remnant of broken souls, drawn to living essence.`;
    case 'boss_name':
      return `NAME: The Shattering Void\nLORE: Ancient beyond reckoning, its form tears reality. None have survived its gaze.\nABILITY: Void Rupture`;
    case 'summon_personality':
      return `PERSONALITY: A stoic warrior who speaks only when battle demands it.\nTRAIT: Unbreakable Resolve`;
    case 'chapter':
      return `STORY: The path before you shimmers with ancient power. A voice echoes through the void, offering knowledge at a price. The choice you make here will ripple through eternity. What will you do?\nCHOICE_A: Accept the power\nCHOICE_B: Refuse the offer\nCHOICE_C: Seek another way`;
  }
}

// ── LLM API callers ───────────────────────────────────────────────────

interface LLMResult { text: string; tokens: number; api: string; }

async function callGroq(prompt: string): Promise<LLMResult> {
  const key = process.env.GROQ_API_KEY;
  if (!key) throw new Error('No GROQ_API_KEY');

  const r = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'llama-3.1-8b-instant',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 150,
      temperature: 0.85,
    }),
  });
  if (!r.ok) throw new Error(`Groq ${r.status}`);
  const d = await r.json() as any;
  return {
    text:   d.choices[0].message.content.trim(),
    tokens: d.usage?.total_tokens ?? 0,
    api:    'groq',
  };
}

async function callCerebras(prompt: string): Promise<LLMResult> {
  const key = process.env.CEREBRAS_API_KEY;
  if (!key) throw new Error('No CEREBRAS_API_KEY');

  const r = await fetch('https://api.cerebras.ai/v1/chat/completions', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'llama3.1-8b',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 150,
      temperature: 0.85,
    }),
  });
  if (!r.ok) throw new Error(`Cerebras ${r.status}`);
  const d = await r.json() as any;
  return {
    text:   d.choices[0].message.content.trim(),
    tokens: d.usage?.total_tokens ?? 0,
    api:    'cerebras',
  };
}

async function callGemini(prompt: string): Promise<LLMResult> {
  const key = process.env.GEMINI_API_KEY;
  if (!key) throw new Error('No GEMINI_API_KEY');

  const r = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: { maxOutputTokens: 150, temperature: 0.85 },
      }),
    }
  );
  if (!r.ok) throw new Error(`Gemini ${r.status}`);
  const d = await r.json() as any;
  const text = d.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
  return {
    text:   text.trim(),
    tokens: d.usageMetadata?.totalTokenCount ?? 0,
    api:    'gemini',
  };
}

// ── Orchestrator: try APIs in order, fall back gracefully ─────────────

async function generate(
  type: AiType, data: Record<string,any>, timeoutMs = 4000
): Promise<LLMResult> {
  const prompt = buildPrompt(type, data);

  const withTimeout = <T>(p: Promise<T>, ms: number): Promise<T> =>
    Promise.race([p, new Promise<T>((_, rej) =>
      setTimeout(() => rej(new Error('timeout')), ms))]);

  // 1. Groq (fastest, best for real-time)
  try {
    return await withTimeout(callGroq(prompt), timeoutMs);
  } catch (e) {
    console.warn('Groq failed:', (e as Error).message);
  }

  // 2. Cerebras (free batch tier)
  try {
    return await withTimeout(callCerebras(prompt), timeoutMs);
  } catch (e) {
    console.warn('Cerebras failed:', (e as Error).message);
  }

  // 3. Gemini (generous daily quota)
  try {
    return await withTimeout(callGemini(prompt), timeoutMs);
  } catch (e) {
    console.warn('Gemini failed:', (e as Error).message);
  }

  // 4. Deterministic fallback — always works, no API needed
  return {
    text:   deterministicFallback(type, data),
    tokens: 0,
    api:    'fallback',
  };
}

// ── Cache key builder ─────────────────────────────────────────────────

function cacheKey(type: AiType, data: Record<string,any>): string {
  // Keys must be stable: sort data fields so argument order doesn't matter
  const relevant: Record<string, any> = {};
  switch (type) {
    case 'loot_name':
      relevant.armor_type = data.armor_type;
      relevant.rarity     = data.rarity;
      relevant.seed       = data.seed;       // same seed → same item
      break;
    case 'enemy_name':
      relevant.level   = Math.floor(data.level / 10) * 10; // bucket by 10
      relevant.context = data.context ?? 'ruins';
      break;
    case 'boss_name':
      relevant.level  = data.level;
      relevant.seed   = data.seed;
      break;
    case 'summon_personality':
      relevant.class_name = data.class_name;
      relevant.tier       = data.tier;
      relevant.seed       = data.seed;
      break;
    case 'chapter':
      relevant.chapter_number    = data.chapter_number;
      relevant.alignment         = data.alignment;
      relevant.previous_choice   = data.previous_choice;
      break;
  }
  return `${type}:${JSON.stringify(relevant)}`;
}

// TTL by type (some content is reusable forever, some is session-specific)
function cacheTtlHours(type: AiType): number | null {
  switch (type) {
    case 'loot_name':          return null;   // permanent (same seed = same item always)
    case 'enemy_name':         return 72;     // 3 days
    case 'boss_name':          return null;   // permanent
    case 'summon_personality': return null;   // permanent
    case 'chapter':            return 168;    // 1 week
  }
}

// ── Public endpoint ───────────────────────────────────────────────────

export default async (req: VercelRequest, res: VercelResponse) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const body: AiRequest = typeof req.body === 'string'
    ? JSON.parse(req.body) : req.body;
  const { type, data } = body;

  if (!type || !data) {
    return res.status(400).json({ error: 'type and data required' });
  }

  try {
    const key = cacheKey(type, data);

    // Try cache first
    const cached = await checkCache(key);
    if (cached) {
      return res.status(200).json({ text: cached, cached: true, api: 'cache' });
    }

    // Generate
    const result = await generate(type, data);

    // Store in cache
    await writeCache(key, type, result.text, result.tokens, result.api,
                     cacheTtlHours(type));

    // Log token usage
    pool.query(
      `INSERT INTO api_usage_log (api_name, tokens_used, cache_hit)
       VALUES ($1, $2, FALSE)`,
      [result.api, result.tokens || 1]
    ).catch(() => {});

    return res.status(200).json({
      text:   result.text,
      cached: false,
      api:    result.api,
    });
  } catch (err: any) {
    console.error('_ai error:', err);
    return res.status(500).json({ error: 'Internal server error' });
  }
};

// ── Named export for internal use from other endpoints ─────────────────
// import { aiGenerate } from './_ai';
// const { text } = await aiGenerate('loot_name', { armor_type, rarity, seed });

export async function aiGenerate(
  type: AiType, data: Record<string,any>, timeoutMs = 3000
): Promise<{ text: string; api: string }> {
  const key = cacheKey(type, data);
  const cached = await checkCache(key);
  if (cached) return { text: cached, api: 'cache' };

  const result = await generate(type, data, timeoutMs);
  await writeCache(key, type, result.text, result.tokens, result.api, cacheTtlHours(type));

  pool.query(
    `INSERT INTO api_usage_log (api_name, tokens_used, cache_hit) VALUES ($1, $2, FALSE)`,
    [result.api, result.tokens || 1]
  ).catch(() => {});

  return { text: result.text, api: result.api };
}